---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

This quarter was interesting as a practitioner of data science as it's not a topic that I have had too much experience with from the lens of a scientist. Since I am a computer science student close to graduation, I've gathered a lot of coding knowledge, but haven't had many chances to utilize code the way a scientist might until this class. Working with R was a new experience for me and I've come to appreciate many of the features of the language and some of the packages created by the R community.

It was very interesting to learn R, and see the similarities and differences from using, say, Pandas in Python. For example, using vectorized functions and joins were very common in Python I learned in DATA 301, but using piping and some general ways of thinking were different. Furthermore, one of the main things I have learned in this class are the importance of tidiness within reports and code when doing statistics using R. In my previous coding classes, the focus has usually been on function over form, so having to consider how other people may read my data analysis was something I had to get used to. My code for plot modifications (DVS-2) and tidy and efficient code (R-2) are examples of learning this for this course. Of course, as addressed in the learning targets, I also learned many topics for data analysis using R.

Other aspects of learning were related to the ungrading scheme of this class. I felt I was constantly trying to improve due to the revisions I would get back every week. I also felt I was rethinking how I approached the class, trying to make sure I fully understood the material rather than attempting a certain grade. Because of personal hardships I experienced towards the end of the quarter, I don't think I was able to fully devote my energy towards learning everything in the course, but I am satisfied with the amount of learning I was able to get done as a student of data science.
