---
title: "Practice activity 9"
author: "Bora Joo"
format: 
  html:
    self-contained: true
    code-tools: true
    code-fold: true
editor: visual
execute:
  echo: true
  error: true
---

```{r}
library(tidyverse)
```

## 9.1 Regression

```{r}
animal <- read_csv(here::here("practice activities", "week9", "mystery_animal.csv"))
```

```{r}
animal_lm <- lm(weight_after ~ weight_before, data = animal)
```

```{r}
animal_lm |>
  broom::augment() |>
  ggplot(mapping = aes(y = .resid, x = .fitted)) +
  geom_point()
```

## 9.2 Simulation

```{r}
qunif(0.95, min = 1.5, max = 3.5)
```

```{r}
qnorm(0.1, mean = 4.6, sd = 0.8)
```

```{r}
pnorm(5, mean = 4.6, sd = 0.8, lower.tail = FALSE)
```

```{r}
pchisq(5, df = 4, lower.tail = FALSE)
```

```{r}
sum(rnorm(100, mean = 4.6, sd = 0.8) < 4)
```

```{r}
set.seed(1957)

music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones) + sum(cornets) + sum(reeds))
}

my_weights <- map_dbl(.x = 1:1000, 
                      .f = ~ music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                      ) 
sum(my_weights < 4532)
```
